/*
 Navicat Premium Data Transfer

 Source Server         : alimysql
 Source Server Type    : MySQL
 Source Server Version : 50719
 Source Host           : 59.110.236.115:3306
 Source Schema         : javaitem-config

 Target Server Type    : MySQL
 Target Server Version : 50719
 File Encoding         : 65001

 Date: 25/02/2021 23:32:49
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 58 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (2, 'application-dev.yml', 'DEFAULT_GROUP', 'web:\r\n  projectDir: D:\\temp\\code\r\nspring:\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  autoconfigure:\r\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\r\n\r\n#请求处理的超时时间\r\nribbon:\r\n  ReadTimeout: 10000\r\n  ConnectTimeout: 10000\r\n\r\n# feign 配置\r\nfeign:\r\n  sentinel:\r\n    enabled: true\r\n  okhttp:\r\n    enabled: true\r\n  httpclient:\r\n    enabled: false\r\n  client:\r\n    config:\r\n      default:\r\n        connectTimeout: 10000\r\n        readTimeout: 10000\r\n  compression:\r\n    request:\r\n      enabled: true\r\n    response:\r\n      enabled: true\r\n\r\n# 暴露监控端点\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'', '6d8586f6aba00a52ea1f4ac117fa4550', '2021-01-13 17:57:46', '2021-01-27 23:32:34', NULL, '0:0:0:0:0:0:0:1', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (6, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf', 'abe5477b7ca5e57559485552827e046a', '2021-01-26 21:40:20', '2021-02-19 13:29:45', NULL, '0:0:0:0:0:0:0:1', '', '', '', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (8, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '#配置\r\nspring:\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: \r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://127.0.0.1:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: 123456\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'ca1c0cf98f1a117fd0c3289b3c0d11a2', '2021-01-26 21:47:47', '2021-02-25 23:29:07', NULL, '0:0:0:0:0:0:0:1', '', '', '系统模块', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (9, 'sentinel-javaitem-gateway', 'DEFAULT_GROUP', '[\r\n    {\r\n        \"resource\": \"javaitem-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-sys\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '106e3ab9566ef2dd713f8bfb9c384b65', '2021-01-26 21:51:31', '2021-02-19 14:31:06', NULL, '0:0:0:0:0:0:0:1', '', '', 'sentinel配置\n', '', '', 'json', '');
INSERT INTO `config_info` VALUES (17, 'javaitem-gen-dev.yml', 'DEFAULT_GROUP', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  contact: \r\n    name: javabb\r\n    url: javabb.cn\r\n    email: javabob@163.com\r\n  authorization:\r\n    name: RuoYi OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '5f91b9e75c2097e3cd7f77f6a3bbaa0b', '2021-02-01 18:14:32', '2021-02-03 14:21:24', NULL, '0:0:0:0:0:0:0:1', '', '', '代码生成模块', '', '', 'yaml', '');
INSERT INTO `config_info` VALUES (21, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', 'spring: \r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: \r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\nswagger:\r\n  title: 系统授权接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn', 'a2269531371582ed1e0ab5cb40dc61a9', '2021-02-03 00:00:08', '2021-02-19 15:39:27', NULL, '0:0:0:0:0:0:0:1', '', '', '认证模块', '', '', 'yaml', '');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 60 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (2, 10, 'application-dev.yml', 'DEFAULT_GROUP', '', 'web:\r\n  projectDir: D:\\temp\\code', '0b6c43051c873a3224cbd943d1b12abc', '2021-01-27 23:00:16', '2021-01-27 23:00:17', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (2, 11, 'application-dev.yml', 'DEFAULT_GROUP', '', 'web:\r\n  projectDir: D:\\temp\\code\r\nspring:\r\n  main:\r\n    allow-bean-definition-overriding: true\r\n  autoconfigure:\r\n    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure\r\n', '79d3f47bb1e0dc2b00c3b6b115de5006', '2021-01-27 23:32:33', '2021-01-27 23:32:34', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 12, 'javaitem-sys.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy/MM/dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: https://javabb.cn\r\n  authorization:\r\n    name: javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'bf05c36c4d590eea30217399d3fa6a2d', '2021-01-27 23:48:34', '2021-01-27 23:48:36', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (12, 13, 'javaitem-sys.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy/MM/dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: https://javabb.cn\r\n  authorization:\r\n    name: javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'bf05c36c4d590eea30217399d3fa6a2d', '2021-01-28 00:11:03', '2021-01-28 00:11:03', NULL, '0:0:0:0:0:0:0:1', 'D', '');
INSERT INTO `his_config_info` VALUES (8, 14, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy/MM/dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: https://javabb.cn\r\n  authorization:\r\n    name: javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'bf05c36c4d590eea30217399d3fa6a2d', '2021-01-28 00:12:54', '2021-01-28 00:12:54', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 15, 'javaitem-componet-gen-dev.yml', 'DEFAULT_GROUP', '', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\', 'ea9aaca8eb0f59c38c14f918b812f921', '2021-01-28 11:29:16', '2021-01-28 11:28:51', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 16, 'javaitem-componet-gen-dev.yml', 'DEFAULT_GROUP', '', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n  authorization:\r\n    name: RuoYi OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'c972c262595ee5d6f10de2ef5a1f0bab', '2021-01-28 11:56:14', '2021-01-28 11:55:50', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 17, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy/MM/dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://localhost:3306/easyweb-security?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n', 'e5b2ee4424da680bead6a7529e0d1137', '2021-01-28 12:17:49', '2021-01-28 12:17:25', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 18, 'javaitem-gen-dev.yml', 'DEFAULT_GROUP', '', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n  contact: \r\n    name: javabb\r\n    url: javabb.cn\r\n    email: javabob@163.com\r\n  authorization:\r\n    name: RuoYi OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '0c7ed2fe45916257c747981c3fff88ac', '2021-02-01 18:15:04', '2021-02-01 18:14:32', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (1, 19, 'javaitem-componet-gen-dev.yml', 'DEFAULT_GROUP', '', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n  contact: \r\n    name: javabb\r\n    url: javabb.cn\r\n    email: javabob@163.com\r\n  authorization:\r\n    name: RuoYi OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '0c7ed2fe45916257c747981c3fff88ac', '2021-02-01 18:15:09', '2021-02-01 18:14:38', NULL, '0:0:0:0:0:0:0:1', 'D', '');
INSERT INTO `his_config_info` VALUES (6, 20, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            # 验证码处理\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n', '42605f743d5329ae58ee4e234fef59f2', '2021-02-02 16:19:46', '2021-02-02 16:19:13', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (9, 21, 'sentinel-javaitem-gateway', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"javaitem-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-sys\",\r\n        \"count\": 1000,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '15929033ae26a2064c9813c1564e20f0', '2021-02-02 16:40:57', '2021-02-02 16:40:25', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 22, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n', '6f2001d677c16a24818f2c4e36c28f05', '2021-02-02 16:42:16', '2021-02-02 16:41:44', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 23, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: ', '3324178292776052621a7d1bef0f75ea', '2021-02-03 00:00:05', '2021-02-03 00:00:08', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (8, 24, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy/MM/dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'e6886f970341725feec5dfa153cbd800', '2021-02-03 10:47:48', '2021-02-03 10:47:14', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 25, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '56a095ec648193beeb3577890022f86f', '2021-02-03 10:49:37', '2021-02-03 10:49:04', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 26, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  #jackson:\r\n  #  time-zone: GMT+8\r\n  #  date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'ff24a44f07a75b2b4664eae083c753de', '2021-02-03 10:50:20', '2021-02-03 10:49:46', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (17, 27, 'javaitem-gen-dev.yml', 'DEFAULT_GROUP', '', 'gen:\r\n  cache: 1\r\n  local: true\r\n  baseDir: D:\\javabb-generator\\\r\n# swagger配置\r\nswagger:\r\n  title: 代码生成接口文档\r\n  license: Powered By ruoyi\r\n  licenseUrl: https://ruoyi.vip\r\n  contact: \r\n    name: javabb\r\n    url: javabb.cn\r\n    email: javabob@163.com\r\n  authorization:\r\n    name: RuoYi OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '0c7ed2fe45916257c747981c3fff88ac', '2021-02-03 14:21:58', '2021-02-03 14:21:24', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 28, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '3b28008658b303bd66abce989b79a3b9', '2021-02-15 17:25:58', '2021-02-15 17:25:57', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 29, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n    - /code\r\n', 'e0792958208671ebb9331410703414ac', '2021-02-15 20:36:10', '2021-02-15 20:36:11', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 30, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n    - /code\r\n', '8844c5199ef426ede60fbed69943f2f8', '2021-02-15 21:12:28', '2021-02-15 21:12:28', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 31, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      globalcors:\r\n        cors-configurations:\r\n          \'[/**]\': \r\n            # 允许携带认证信息\r\n            # 允许跨域的源(网站域名/ip)，设置*为全部\r\n            # 允许跨域请求里的head字段，设置*为全部\r\n            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部\r\n            # 跨域允许的有效期\r\n            allow-credentials: true\r\n            allowed-origins: \r\n            - \"http://localhost\"\r\n            - \"http://localhost:8081\"\r\n            allowed-headers: \"*\"\r\n            allowed-methods: \r\n            - OPTIONS\r\n            - GET\r\n            - POST\r\n            max-age: 3600\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n    - /code\r\n', '3b719a9507d73db2f8b1890dcdd6ae2f', '2021-02-15 21:14:19', '2021-02-15 21:14:19', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 32, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      globalcors:\r\n        cors-configurations:\r\n          \'[/**]\': \r\n            # 允许携带认证信息\r\n            # 允许跨域的源(网站域名/ip)，设置*为全部\r\n            # 允许跨域请求里的head字段，设置*为全部\r\n            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部\r\n            # 跨域允许的有效期\r\n            allow-credentials: true\r\n            allowed-origins: \r\n            - \"*\"\r\n            allowed-headers: \"*\"\r\n            allowed-methods: \r\n            - OPTIONS\r\n            - GET\r\n            - POST\r\n            max-age: 3600\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/code/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n    - /code\r\n', 'a7f0ea9ca0f31109cf2f9f592ea8be49', '2021-02-16 11:44:24', '2021-02-16 11:44:25', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 33, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '3fb8352a297415905e49de34d5fbae75', '2021-02-16 15:08:24', '2021-02-16 15:08:25', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 34, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '65f3f5feb27d7a97362fcbcc172a8025', '2021-02-19 10:03:47', '2021-02-19 10:03:47', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 35, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - Header={header}, \\d+\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', 'fdaf93fb298d28a649a46956162800d3', '2021-02-19 10:04:40', '2021-02-19 10:04:40', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 36, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - Header={user_id}, \\d+\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '55d7a404af4c6b8e7f8224ad9aa9969b', '2021-02-19 10:06:38', '2021-02-19 10:06:38', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 37, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '65f3f5feb27d7a97362fcbcc172a8025', '2021-02-19 10:51:37', '2021-02-19 10:51:36', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 38, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password:\r\n# json时间格式设置\r\n  #jackson:\r\n  #  time-zone: GMT+8\r\n  #  date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'ff24a44f07a75b2b4664eae083c753de', '2021-02-19 10:52:01', '2021-02-19 10:52:00', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (21, 39, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: ', '3324178292776052621a7d1bef0f75ea', '2021-02-19 10:52:22', '2021-02-19 10:52:21', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 40, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - CacheRequestFilter\r\n            - ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '9c2bd34eb428764fe14189679a6535b4', '2021-02-19 10:55:37', '2021-02-19 10:55:37', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 41, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', 'c1062b1a4bc3adcaf1fa4c8ed3b9d502', '2021-02-19 11:03:44', '2021-02-19 11:03:44', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 42, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '29b1501ffa761eeaf5207a0435fddb6a', '2021-02-19 11:05:46', '2021-02-19 11:05:46', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 43, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', 'c1062b1a4bc3adcaf1fa4c8ed3b9d502', '2021-02-19 11:07:06', '2021-02-19 11:07:05', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 44, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', 'f766c96c1be891f8dc9ca0840bd45cb7', '2021-02-19 11:08:41', '2021-02-19 11:08:41', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 45, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', 'c1062b1a4bc3adcaf1fa4c8ed3b9d502', '2021-02-19 11:13:52', '2021-02-19 11:13:52', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 46, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password:\r\n# json时间格式设置\r\n  #jackson:\r\n  #  time-zone: GMT+8\r\n  #  date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', '14e625b6dd43543c5d3fb1b479c89420', '2021-02-19 11:14:00', '2021-02-19 11:14:00', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (21, 47, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: ', 'aa8da614e685c19b83310dfb50d393b3', '2021-02-19 11:14:28', '2021-02-19 11:14:27', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 48, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111\r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n    - /sys/user/**\r\n', '4253d3fa05ea4c29aa754a88bc80f31a', '2021-02-19 11:25:04', '2021-02-19 11:25:04', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 49, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111\r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf\r\n', 'db7bbe338d94304cd63e2f1136609bba', '2021-02-19 11:46:26', '2021-02-19 11:46:25', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 50, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111\r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf', '4f1301ede7666f1d767189b16d0a1b68', '2021-02-19 11:55:38', '2021-02-19 11:55:37', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 51, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111\r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf', '4f1301ede7666f1d767189b16d0a1b68', '2021-02-19 11:56:06', '2021-02-19 11:56:06', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 52, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111\r\n# json时间格式设置\r\n  #jackson:\r\n  #  time-zone: GMT+8\r\n  #  date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'dd5ae47eb404ede8fdbec3c8e140af2d', '2021-02-19 11:59:37', '2021-02-19 11:59:37', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (21, 53, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: 10.0.0.10\r\n    port: 63790\r\n    password: aaaaB1111', 'd2139918f02134190f72350cf8f8cc53', '2021-02-19 11:59:58', '2021-02-19 11:59:58', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 54, 'javaitem-gateway-dev.yml', 'DEFAULT_GROUP', '', 'spring:\r\n  redis:\r\n    host: localhost\r\n    port: 6379\r\n    password: \r\n  cloud:\r\n    gateway:\r\n      discovery:\r\n        locator:\r\n          lowerCaseServiceId: true\r\n          enabled: true\r\n      routes:\r\n        # 认证中心\r\n        - id: javaitem-auth\r\n          uri: lb://javaitem-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            #- CacheRequestFilter\r\n            #- ValidateCodeFilter\r\n            - StripPrefix=1\r\n        # 代码生成\r\n        - id: javaitem-gen\r\n          uri: lb://javaitem-gen\r\n          predicates:\r\n            - Path=/gen/**\r\n          filters:\r\n            - StripPrefix=1\r\n        # 系统模块\r\n        - id: javaitem-sys\r\n          uri: lb://javaitem-sys\r\n          predicates:\r\n            - Path=/sys/**\r\n          filters:\r\n            - StripPrefix=1\r\n\r\n# 不校验白名单\r\nignore:\r\n  whites:\r\n    - /auth/logout\r\n    - /auth/login\r\n    - /*/v2/api-docs\r\n    - /csrf', '805cc44ece16c9c1a694704001af5736', '2021-02-19 13:29:45', '2021-02-19 13:29:45', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 55, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: \r\n# json时间格式设置\r\n  #jackson:\r\n  #  time-zone: GMT+8\r\n  #  date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'fbecff6621e1a33a3f52c37686059015', '2021-02-19 14:21:39', '2021-02-19 14:21:38', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (21, 56, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: ', '7ea8af4524d9ded2c4f315e2b92eb32e', '2021-02-19 14:26:54', '2021-02-19 14:26:54', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (9, 57, 'sentinel-javaitem-gateway', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        \"resource\": \"javaitem-auth\",\r\n        \"count\": 500,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-sys\",\r\n        \"count\": 2,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    },\r\n	{\r\n        \"resource\": \"javaitem-gen\",\r\n        \"count\": 200,\r\n        \"grade\": 1,\r\n        \"limitApp\": \"default\",\r\n        \"strategy\": 0,\r\n        \"controlBehavior\": 0\r\n    }\r\n]', '55ad5641c3138e1aa069e80efef0f321', '2021-02-19 14:31:06', '2021-02-19 14:31:06', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (21, 58, 'javaitem-auth-dev.yml', 'DEFAULT_GROUP', '', 'spring: \r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: \r\nswagger:\r\n  title: 系统授权接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn', 'fe3f4ab27105cb69b856cc64c29d61b9', '2021-02-19 15:39:26', '2021-02-19 15:39:27', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (8, 59, 'javaitem-sys-dev.yml', 'DEFAULT_GROUP', '', '#配置\r\nspring:\r\n  redis:\r\n    host: 127.0.0.1\r\n    port: 6379\r\n    password: \r\n# json时间格式设置\r\n  jackson:\r\n    time-zone: GMT+8\r\n    date-format: yyyy-MM-dd HH:mm:ss\r\n  # 设置上传文件大小\r\n  servlet:\r\n    multipart.max-file-size: 100MB\r\n    multipart.max-request-size: 100MB\r\n  # 连接池配置\r\n  datasource:\r\n    url: jdbc:mysql://59.110.236.115:3306/javaitem-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8\r\n    username: root\r\n    password: mima123\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    type: com.alibaba.druid.pool.DruidDataSource\r\n    druid:\r\n      initial-size: 5\r\n      min-idle: 5\r\n      max-active: 20\r\n      max-wait: 30000\r\n      time-between-eviction-runs-millis: 60000\r\n      min-evictable-idle-time-millis: 300000\r\n      test-while-idle: true\r\n      test-on-borrow: true\r\n      test-on-return: false\r\n      remove-abandoned: true\r\n      remove-abandoned-timeout: 1800\r\n      #pool-prepared-statements: false\r\n      #max-pool-prepared-statement-per-connection-size: 20\r\n      filters: stat,wall\r\n      validation-query: SELECT \'x\'\r\n      stat-view-servlet:\r\n        url-pattern: /druid/*\r\n        reset-enable: true\r\n        login-username: admin\r\n        login-password: admin\r\n\r\n# Mybatis-plus配置\r\nmybatis-plus:\r\n  mapper-locations: classpath:cn/javabb/**/*Mapper.xml\r\n  typeAliasesPackage: cn.javabb.**.entity\r\n  global-config:\r\n    id-type: 0\r\n    field-strategy: 1\r\n    db-column-underline: true\r\n    logic-delete-value: 1\r\n    logic-not-delete-value: 0\r\n  configuration:\r\n    map-underscore-to-camel-case: true\r\n    cache-enabled: false\r\n# swagger配置\r\nswagger:\r\n  title: 系统模块接口文档\r\n  license: Powered By javabb\r\n  licenseUrl: http://javabb.cn\r\n  authorization:\r\n    name: Javabb OAuth\r\n    auth-regex: ^.*$\r\n    authorization-scope-list:\r\n      - scope: server\r\n        description: 客户端授权范围\r\n    token-url-list:\r\n      - http://localhost:8080/auth/oauth/token', 'ed30cc9a595fde836b7e1b8e4a4606a2', '2021-02-25 23:29:07', '2021-02-25 23:29:07', NULL, '0:0:0:0:0:0:0:1', 'U', '');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `resource` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
